name: eval

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to evaluate (supports fork PRs)'
        required: false
        type: string
      submission_name:
        description: 'Name for this submission (e.g. "my_submission")'
        required: false
        type: string
      submission_url:
        description: 'Link to submission zip (e.g. https://github.com/user-attachments/files/26130120/submission.zip)'
        required: true
        type: string
      runner:
        description: 'Runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  test:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ inputs.pr_number && format('refs/pull/{0}/merge', inputs.pr_number) || 'master' }}

      - name: Check GPU
        if: ${{ inputs.runner == 'self-hosted' }}
        run: |
          nvidia-smi

       # TODO: make an arg
      - name: Download submission
        run: |
          mkdir -p ./submissions/baseline
          curl -L -o ./submissions/baseline/archive.zip "${{ inputs.submission_url }}"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies (cpu)
        run: uv sync --group cpu

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # TODO: make an arg
      - name: Evaluate
        run: uv run --group cpu bash evaluate.sh --device cpu --submission-dir ./submissions/baseline
